# Generated by Django 4.2.6 on 2024-01-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validity', models.IntegerField()),
                ('expiration_time', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('endpoint', models.SlugField()),
            ],
        ),
    ]
