# Generated by Django 4.2.6 on 2024-01-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_data',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='endpoint',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='validity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
