# Generated by Django 4.2.6 on 2024-01-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempupload', '0002_remove_uploadedfile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_data',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
