# Generated by Django 4.2.6 on 2024-01-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempupload', '0003_alter_uploadedfile_file_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_data',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='endpoint',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='validity',
            field=models.IntegerField(null=True),
        ),
    ]
