# Generated by Django 4.2.6 on 2024-02-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempupload', '0005_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
